# Generated by Django 6.0.4 on 2026-04-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempost',
            name='claimed',
            field=models.BooleanField(default=False),
        ),
    ]
