# Generated by Django 6.0.4 on 2026-04-26 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_initial'),
        ('items', '0002_itempost_claimed'),
    ]

    operations = [
    ]
