# Generated by Django 6.0.4 on 2026-04-26 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_itempost_claimed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempost',
            name='resolved',
        ),
    ]
