# Generated by Django 6.0.4 on 2026-04-26 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_merge_0002_initial_0002_itempost_claimed'),
        ('items', '0003_remove_itempost_resolved'),
    ]

    operations = [
    ]
