# Generated by Django 6.0.4 on 2026-04-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_remove_itempost_resolved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='itempost',
            name='tags',
            field=models.ManyToManyField(to='items.tag'),
        ),
    ]
