# Generated by Django 6.0.4 on 2026-04-28 14:11

from django.db import migrations

def create_tags(apps, schema_editor):
    Tag = apps.get_model('items', 'Tag')

    tags = [
        "pet",
        "electronics",
        "wallet",
        "documents",
        "keys",
        "other"
    ]

    for name in tags:
        Tag.objects.get_or_create(name=name)

class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_tag_itempost_tags'),
    ]

    operations = [
        migrations.RunPython(create_tags),
    ]