# Generated by Django 6.0.4 on 2026-04-29 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_merge_20260426_1837'),
        ('items', '0005_seed_tags'),
    ]

    operations = [
    ]
